title:       The 30th Annual Fall Workshop on Computational Geometry
description: North Carolina State University

timezone: Eastern Daylight Time

navigation:
  Home: "/fwcg2022"
  Committees: "/fwcg2022/committee"
  Call for Papers: "/fwcg2022/cfp"
  Registration: "/fwcg2022/registration"
  Schedule: "/fwcg2022/schedule"
  Invited Speakers: "/fwcg2022/speakers"
  Travel Support: "/fwcg2022/travel_support"
  Travel Information: "/fwcg2022/localinfo"
  Zoom: "/fwcg2022/zoom"
  Code of Conduct: "/fwcg2022/codeofconduct"

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
